# Generated by Django 5.2.7 on 2025-10-10 23:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del artículo')),
                ('categoria', models.CharField(choices=[('llave', 'Llave'), ('aula', 'Aula'), ('documento', 'Documento'), ('equipo', 'Equipo'), ('proyecto', 'Proyecto'), ('otro', 'Otro')], max_length=50, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponible')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación física')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('apellidopaterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellidomaterno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('tipo', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de prestatario')),
                ('carrera_o_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrera o área')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Prestatario',
                'verbose_name_plural': 'Prestatarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_usuario', models.TextField(verbose_name='Mensaje del usuario')),
                ('respuesta_bot', models.TextField(blank=True, null=True, verbose_name='Respuesta del chatbot')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de interacción')),
                ('prestatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incos_app.prestatario', verbose_name='Prestatario')),
            ],
            options={
                'verbose_name': 'Interacción del chatbot',
                'verbose_name_plural': 'Interacciones del chatbot',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_reservada', models.DateField(verbose_name='Fecha para la reserva')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('vencido', 'Vencido')], default='activo', max_length=20, verbose_name='Estado de la reserva')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incos_app.articulo', verbose_name='Artículo reservado')),
                ('prestatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incos_app.prestatario', verbose_name='Prestatario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo institucional')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('superadmin', 'Super Administrador')], default='admin', max_length=20, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='incos_admin_groups', related_query_name='incos_admin', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='incos_admin_permissions', related_query_name='incos_admin', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de préstamo')),
                ('fecha_prevista_devolucion', models.DateField(verbose_name='Fecha prevista de devolución')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha real de devolución')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('devuelto', 'Devuelto'), ('retrasado', 'Retrasado'), ('perdido', 'Perdido')], default='en_curso', max_length=20, verbose_name='Estado del préstamo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incos_app.articulo', verbose_name='Artículo')),
                ('prestatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Incos_app.prestatario', verbose_name='Prestatario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Administrador responsable')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
