# Generated by Django 5.2.7 on 2025-10-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Incos_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="fecha_devolucion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha y hora prevista de devolución",
            ),
        ),
    ]
