# Generated by Django 5.2.7 on 2025-10-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Incos_app", "0002_alter_prestamo_fecha_devolucion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="fecha_devolucion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha y hora real de devolución"
            ),
        ),
        migrations.AlterField(
            model_name="prestamo",
            name="fecha_prevista_devolucion",
            field=models.DateTimeField(
                verbose_name="Fecha y hora prevista de devolución"
            ),
        ),
    ]
