# Generated by Django 5.2.7 on 2025-10-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Incos_app", "0003_alter_prestamo_fecha_devolucion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestatario",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                help_text="El ID único del chat de Telegram del usuario para notificaciones.",
                max_length=50,
                null=True,
                verbose_name="Telegram Chat ID",
            ),
        ),
    ]
