# Generated by Django 5.2.7 on 2025-10-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Incos_app", "0004_prestatario_telegram_chat_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reserva",
            options={
                "ordering": ["fecha_inicio"],
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
            },
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="fecha_reservada",
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha_fin",
            field=models.DateTimeField(
                default="2000-01-01 00:00",
                verbose_name="Fecha y hora de fin de la reserva",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha_inicio",
            field=models.DateTimeField(
                default="2000-01-01 00:00",
                verbose_name="Fecha y hora de inicio de la reserva",
            ),
            preserve_default=False,
        ),
    ]
