"""
Django settings for Incos project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path

# ============================================================
# RUTAS BASE
# ============================================================
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# CONFIGURACIÓN BÁSICA
# ============================================================
SECRET_KEY = 'django-insecure-=p4(b!e9_$#d7pi4#^i1as9yp&tggv*as5uq_$%d#17_%7oi^4'
DEBUG = True
ALLOWED_HOSTS = []


# ============================================================
# APLICACIONES INSTALADAS
# ============================================================
INSTALLED_APPS = [
    # Apps de Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Incos_app',
]


# ============================================================
# MIDDLEWARE
# ============================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# CONFIGURACIÓN DE URLS Y WSGI
# ============================================================
ROOT_URLCONF = 'Incos.urls'
WSGI_APPLICATION = 'Incos.wsgi.application'


# ============================================================
# CONFIGURACIÓN DE TEMPLATES
# ============================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Carpeta global para tus plantillas
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# BASE DE DATOS (PostgreSQL)
# ============================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Incos',         # Nombre de la base de datos
        'USER': 'postgres',      # Usuario de PostgreSQL
        'PASSWORD': 'admin123',  # Contraseña
        'HOST': 'localhost',     # Servidor
        'PORT': '5432',          # Puerto por defecto de PostgreSQL
    }
}


# ============================================================
# VALIDACIÓN DE CONTRASEÑAS
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ============================================================
# INTERNACIONALIZACIÓN Y LOCALIZACIÓN
# ============================================================
LANGUAGE_CODE = 'es'  # Español
TIME_ZONE = 'America/La_Paz'  # Zona horaria de Bolivia
USE_I18N = True
USE_TZ = True

# Carpeta para archivos de traducción
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# ============================================================
# ARCHIVOS ESTÁTICOS (CSS, JS, IMÁGENES)
# ============================================================
STATIC_URL = 'static/'


# ============================================================
# CONFIGURACIÓN DE MODELO DE USUARIO PERSONALIZADO
# ============================================================
AUTH_USER_MODEL = 'Incos_app.Usuario'


# ============================================================
# AUTENTICACIÓN Y REDIRECCIONES
# ============================================================
LOGIN_URL = '/'                 # Página de login
LOGIN_REDIRECT_URL = 'inicio'   # Redirección tras login exitoso
LOGOUT_REDIRECT_URL = '/'       # Redirección tras logout


# ============================================================
# CONFIGURACIÓN DE EMAIL (para recuperación de contraseñas)
# ============================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'marcelchucaespinoza123321@gmail.com'   # Tu correo de envío
EMAIL_HOST_PASSWORD = 'xtmb ukuw uimn xubu'               # Contraseña de aplicación de Gmail


# ============================================================
# CONFIGURACIÓN DE CLAVE PRIMARIA POR DEFECTO
# ============================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
